Description: >
  This template deploys a VPC, with a pair of public and database subnets spread
  across two Availability Zones. It deploys an Internet Gateway, with a default
  route on the public subnets.

Parameters:
  SSHKey:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Provide an SSH KeyName to allow SSH access to the instances
  HomeIp:
    Type: String
    Description: My IP
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
  DBUser:
    Type: String
    Description: Database master user for RDS
    Default: postgres
    NoEcho: true
  DBPassword:
    Type: String
    Description: Password for database master user for RDS
    Default: postgres
    NoEcho: true
    MinLength: 1
    MaxLength: 41
  CloudformationBucket:
    Type: String
    Description: CloudFormation bucket name
    Default: https://eugene-ivanov-web-app-cloudformation-templates.s3.eu-west-2.amazonaws.com

Resources:
  MASTER:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join ["/", [!Ref CloudformationBucket, "infrastructure/master/master.yaml"]]
      Parameters:
        EnvironmentName: "WebApp-QA"
        SSHKey: !Ref SSHKey
        HomeIp: !Ref HomeIp
        DBUser: !Ref DBUser
        DBPassword: !Ref DBPassword
        CloudformationBucket: !Ref CloudformationBucket
